replicaCount: 1

image:
  repository: rpadallery/fastapiapp
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: 
  - name: "regcred"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources: {}
